### ISSUE TITLE
Atraso na disponibilização

### ISSUE THREAD

**Issue by r-gaia-cs** [rafaeusantana/docsolr#13]
Via [lista okf-br](https://lists.okfn.org/pipermail/okfn-br/2014-November/004800.html):

> Eu vi que eles estão publicando os dados, mas ainda tão com um atraso de 3 dias.
>
> Faz idéia se eles vão manter isso desse jeito, fora isso não achei em nehum lugar um feed dessas noticias.
>
> Será que tem?

**Comment by andresmrm** [comment]
O pessoal do LabProdam automatizou o repasse dos diários para o nosso servidor. Não devemos ter mais atrasos na disponibilização, pelo menos não por esse motivo...
Obrigado pelo interesse, @hrangel. =)
