### ISSUE TITLE
Pensar na forma como o Google indexa o diário livre

### ISSUE THREAD

**Issue by rafaeusantana** [rafaeusantana/docsolr#18]
Na minha visão, o Google deveria indexar somente os artigos. Não deveria indexar os resultados de busca (um resultado de busca que tem um link para outro resultado de busca), e nem deveria indexar os .xml e .json.

**Comment by rafaeusantana** [comment]
Eu acho que os artigos isolados têm que ter prioridade sim. Não tem muito sentido retornar uma busca dentro de outra busca. Se a informação pode ser retornada em um clique, acho melhor assim. E muitos usuários podem entrar na página de busca e se perderem com outras informações inúteis.

Fiz o commit para bloquear a indexação das buscas e dos links de exportação.

**Comment by andresmrm** [comment]
No ar em:
http://devcolab.each.usp.br/do/robots.txt
Mas não sei se esse é o lugar certo para esse arquivo. Você sabe?

**Comment by andresmrm** [comment]
Uma outra dúvida que tenho: como os indexadores chegam nos artigos? Não é pelos links na página de busca (filtros)?

**Comment by rafaeusantana** [comment]
Então, tem que colocar o robots.txt na pasta raiz http://devcolab.each.usp.br.

Eu pensei que o robots.txt só evitava a indexação, mas agora vi que ele também bloqueia o crawling das páginas. A solução que encontrei foi colocar um meta tag com noindex no html quando for busca.

O bloqueio dos links de exportação continua valendo através do robots.txt.

**Comment by andresmrm** [comment]
Novo código no ar e robots na raiz:
http://devcolab.each.usp.br/robots.txt
