### ISSUE TITLE
Busca retornando resultados sem um dos termos procurados

### ISSUE THREAD

**Issue by andresmrm** [rafaeusantana/docsolr#21]
@rafaeusantana , isso era esperado?

Por exemplo essa [busca](http://devcolab.each.usp.br/do/?utf8=%E2%9C%93&q=Fabiano+Ang%C3%A9lico&date_range=data:%5B2010-05-29T00:00:00.000Z%20TO%202010-05-29T00:00:00.000Z%5D&f%5Bdata%5D%5B%5D=date_range) possui dois termos, mas 2 dos resultados retornados, só possuem um dos termos. Tanto que eles nem mostram nada em negrito no techo de texto que aparece.

**Comment by andresmrm** [comment]
Tem mais gente reclamando disso... Talvez fosse o caso de avaliarmos se há como deixar isso configurável para cada busca.

**Comment by ppKrauss** [comment]
A busca é ruim pois faz operação de **OR** entre as palavras, quando o default deveria ser **AND**. "A and B" é mais restritivo, retorna menos lixo do que "A or B". Deve ser bobagem de configuração do Solr.

**Comment by ppKrauss** [comment]
@rafaeusantana , desculpe não ter lido com atenção seu texto. Gostaria de esclarecer o seguinte:

* na Teoria da Recuperação da Informação, existem os conceitos de  [precision e recall](https://en.wikipedia.org/wiki/Precision_and_recall), que são também fatores que o usuário sempre quer otimizar. As pesquisar AND elevam **precision** (!),  não é por acaso que em TODAS as boas ferramentas de busca o AND é o default (o espaço em branco faz papel de operador AND).

* a pesquisa avançada deveria esclarecer qual a sintaxe de AND e OR para o usuário decidir o que quer e fazer coisas mais exóticas.

portanto acho correto estar reabrindo o chamado e **solicitando a correção**.

**Comment by ppKrauss** [comment]
Gente, um projeto tão importante, e um problema tão simples de ser resolvido... **Está abandonado??**

**Comment by andresmrm** [comment]
Oi, @ppKrauss! Então... eu cheguei o conversar com o @rafaeusantana sobre isso. Mas a outra saída que ele comentou, pelo que me lembro, também não era muito boa. Se o Rafael quiser explicar melhor aqui...

E, da minha parte, ultimamente, com a correria no desenvolvimento do Cuidando, não tenho conseguido mexer no Diário Livre não. O máximo que faço é botar um Uptimebot para me avisar quando o site cai e reiniciar o Solr quando vejo o e-mail de aviso.

@campagnucci, como resolveu essa questão da busca AND/OR no Pedido Respondido? A propósito, parabéns pelo trabalho com ele! =)

**Comment by andresmrm** [comment]
Acho que arrumei. Adicionei um:

```
<str name="q.op">AND</str>
```

Aqui:

```
[...]
<requestHandler name="/select" class="solr.SearchHandler">
    <!-- default values for query parameters can be specified, these
         will be overridden by parameters in the request
      -->
     <lst name="defaults">
       <str name="echoParams">explicit</str>
       <int name="rows">10</int>
       <str name="q.op">AND</str>
       <str name="df">text</str>
     </lst>
[...]
```

No arquivo: `/etc/solr/conf/solrconfig.xml`. E reiniciei o servidor.

Mas parece que agora as vezes ele manda para a página inicial com a mensagem "Desculpe, Eu não compreendi sua busca". **Acho** que isso só acontece em algumas das vezes quando não acha nada. De qualquer forma não parece o comportamento correto.

Se acharem que está funcionando, fechem a issue.

**Comment by ppKrauss** [comment]
@andresmrm  Fazendo busca por `meio ambiente parque aclimação`  melhorou bastante (!), mas ainda estranho trazer textos no final (páginação 218) sem nenhuma das palavras-chave.

**Comment by andresmrm** [comment]
@ppKrauss Replicando sua busca e pegando a última página:
http://devcolab.each.usp.br/do/?page=218&q=meio+ambiente+parque+aclima%C3%A7%C3%A3o&utf8=%E2%9C%93
Ela só tem um artigo:
http://devcolab.each.usp.br/do/2003/05/20/132
E esse artigo tem as quatro palavras da busca (separadas) (aclimação está sem acentuação).

**Comment by ppKrauss** [comment]
Ops, desculpe o teste corrido @andresmrm , faltava eu clicar para ver o imenso texto. Sim, perfeito (!).

 Bom, acho que podemos dar por fechada a _issue_... 

---

... e dar por **finalmente aberta a temporada de uso** da ferramenta, que até ontem era só um brinquedo ruim. A partir de agora **os  _logs_ de acesso** passam a ter relevância. Vale a pena convidar usuários que no passado vislumbraram grandes possibilidades de uso, para voltarem, assim como colocar um aviso na página "buscas mais precisas!".

**Comment by andresmrm** [comment]
Que exagero, Peter... =P Duvido que essa mudança afete tanto o uso da ferramenta.
Fechando a issue.
